files:
  - source: /airsync-mac/Localization/en.json
    translation: /airsync-mac/Localization/%two_letters_code%.json
    type: json
    languages_mapping:
      two_letters_code:
        zh-CN: zh-Hans
        zh-TW: zh-Hant
preserve_hierarchy: 1
